server:
  port: 8095

spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/postgresDB
    username: postgres
    password: Admin@123


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
